version: '3'

services:
  web:
    build: .
    container_name: warehouse
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - HOST=0.0.0.0
      - DOCKER_BUILDKIT=0
    volumes:
      - .:/app


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/certificate.crt:/etc/ssl/certs/certificate.crt
      - ./ssl/private.key:/etc/ssl/private/private.key
      - ./ssl/ca_bundle.crt:/etc/ssl/certs/ca_bundle.crt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

