version: '3'

services:
  web:
    build: .
    container_name: warehouse
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - HOST=0.0.0.0
      - DOCKER_BUILDKIT=0
    volumes:
      - .:/app
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/certificate.cert:/etc/ssl/certs/certificate.cert
      - /etc/ssl/private/private.pem:/etc/ssl/private/private.pem
      - /etc/ssl/certs/dv_ca.pem:/etc/ssl/certs/dv_ca.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
