# Generated by Django 5.1.4 on 2024-12-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_operation_customer_alter_operation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cut_off',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
