# Generated by Django 5.1.4 on 2024-12-15 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_operation_cut_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='created_objects', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez'),
            preserve_default=False,
        ),
    ]
