# Generated by Django 5.1.4 on 2024-12-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_operation_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='created_by',
            new_name='user',
        ),
    ]
