# Generated by Django 5.1.4 on 2024-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
