# Generated by Django 5.1.4 on 2024-12-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_operation_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
