# Generated by Django 5.1.4 on 2024-12-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_operation_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='cargo_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('pallets_loading', 'Zał. paletowy'), ('manual_loading', 'Zał. ręczny'), ('unloading', 'Rozładunek')], default='loading', max_length=15, verbose_name='Typ operacji'),
        ),
    ]
