# Generated by Django 5.1.4 on 2025-01-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_operation_cargo_name_alter_operation_operation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('man_hour_type', models.CharField(choices=[('standard', 'Standardowy'), ('exceptional', 'Wyjątkowy')], default='standard', max_length=20, verbose_name='man_hour_type')),
            ],
        ),
    ]
